blueprint:
  name: Uber Eats Active Order Updates TTS Blueprint
  description: >-
    ### Uber Eats Active Order Updates TTS Blueprint

    ![Uber Eats Banner](https://raw.githubusercontent.com/zodyking/uber-eats-order-tracker/main/image.png)

    This blueprint creates an automation that announces changes to Uber Eats order sensors when an active order is detected.  
    It triggers on updates to order stage, driver name, driver ETA/ETT, driver location, a periodic delivery-updates timer, and active order status,  
    and uses TTS to speak customized messages.

    **Version:** 1.3.2

    **Key Features:**  
    * Announces new orders with restaurant name.  
    * Announces when a driver is assigned.  
    * Announces order stage changes (picked up, en route, arriving, delivered).  
    * Delivery updates driven by a configurable time pattern (minutes).  
    * Robust delivery-update condition to skip “No Driver Assigned / No ETT Available”.  
    * Queued mode to avoid overlapping TTS playback.

    **Requirements:**  
    * Uber Eats Order Tracking integration installed and configured.  
    * A TTS engine configured in Home Assistant (e.g., Google Translate TTS).  
    * Media player entities to play announcements.

    **Notes:**  
    * Select the correct “Uber Eats” entities manually (blueprints can’t filter by label).  
    * Ensure your Uber Eats sensors update their **state** (not only attributes).

  domain: automation

  input:
    # General
    user_name:
      name: User Name
      description: The user's name to include in TTS messages (e.g., Brandon)
      selector:
        text:

    # Active order binary sensor
    active_order_sensor:
      name: Active Order Binary Sensor
      description: Must be "on" when there is an active order.
      selector:
        entity:
          domain: binary_sensor

    # Core stage/name sensors
    order_stage_sensor:
      name: Order Stage Sensor
      description: e.g., picked up, en route, arriving, delivered
      selector:
        entity:
          domain: sensor

    driver_name_sensor:
      name: Driver Name Sensor
      selector:
        entity:
          domain: sensor

    # ETA / ETT + restaurant
    driver_eta_sensor:
      name: Driver ETA Sensor (clock time)
      description: e.g., "5:42 PM"
      selector:
        entity:
          domain: sensor

    driver_ett_sensor:
      name: Driver ETT Sensor (minutes remaining)
      description: e.g., "12 minutes"
      selector:
        entity:
          domain: sensor

    restaurant_name_sensor:
      name: Restaurant Name Sensor
      selector:
        entity:
          domain: sensor

    # Location group (new sensors)
    driver_location_sensor:
      name: Driver Location Sensor (address/cross-street)
      selector:
        entity:
          domain: sensor

    driver_address_sensor:
      name: Driver Address Sensor
      selector:
        entity:
          domain: sensor

    driver_street_sensor:
      name: Driver Street Sensor
      selector:
        entity:
          domain: sensor

    driver_quarter_sensor:
      name: Driver Borough/Quarter Sensor
      selector:
        entity:
          domain: sensor

    driver_suburb_sensor:
      name: Driver Suburb Sensor
      selector:
        entity:
          domain: sensor

    driver_county_sensor:
      name: Driver County Sensor
      selector:
        entity:
          domain: sensor

    latest_arrival_sensor:
      name: Latest Arrival Sensor
      selector:
        entity:
          domain: sensor

    # Delivery updates cadence (time_pattern)
    delivery_updates_minutes:
      name: Delivery Updates Interval (minutes)
      description: How often to announce delivery updates (time-pattern trigger).
      default: 2
      selector:
        number:
          min: 1
          max: 30
          step: 1
          mode: slider
          unit_of_measurement: minutes

    # TTS / media
    tts_players:
      name: TTS Media Players
      description: Media players to play announcements on.
      selector:
        entity:
          domain: media_player
          multiple: true

    tts_engine:
      name: TTS Engine
      selector:
        entity:
          domain: tts

    tts_volume:
      name: TTS Volume
      description: Volume level for the media players (0.0 to 1.0)
      default: 0.3
      selector:
        number:
          min: 0.0
          max: 1.0
          step: 0.01
          mode: slider

# -------------------- TRIGGERS --------------------
trigger:
  - platform: state
    entity_id: !input order_stage_sensor
    id: order_stage_change

  - platform: state
    entity_id: !input driver_name_sensor
    id: driver_name_change

  - platform: state
    entity_id: !input driver_location_sensor
    id: driver_location_change

  - platform: state
    entity_id: !input active_order_sensor
    id: active_order_change

  - alias: Delivery Updates
    platform: time_pattern
    id: Delivery_Updates
    minutes: !input delivery_updates_minutes

# -------------------- GUARD --------------------
condition:
  - condition: state
    entity_id: !input active_order_sensor
    state: "on"

# -------------------- ACTIONS --------------------
action:
  - variables:
      user_name: !input user_name
      active_order_sensor: !input active_order_sensor
      order_stage_sensor: !input order_stage_sensor
      driver_name_sensor: !input driver_name_sensor
      driver_eta_sensor: !input driver_eta_se
