blueprint:
  name: Uber Eats Active Order Updates TTS Blueprint
  description: >-
    ### Uber Eats Active Order Updates TTS Blueprint

    ![Uber Eats Banner](https://raw.githubusercontent.com/zodyking/uber-eats-order-tracker/main/image.png)

    This blueprint creates an automation that announces changes to Uber Eats order sensors when an active order is detected.  
    It triggers on updates to order stage, driver name, ETA/ETT, location, a periodic delivery-updates timer, and active order status,  
    and uses TTS to speak customized messages.


    **Version:** 1.3.5  


    **Key Features:**  
    
    * Announces new orders with restaurant name.  
    
    * Announces when a driver is assigned.  
    
    * Announces order stage changes (picked up, en route, arriving, delivered).  
    
    * Delivery updates driven by a configurable time pattern (minutes).  
    
    * Location updates use Borough/Quarter + Suburb + **Driver Street** (cross-street) with robust “not No Driver/ETT/ETA” checks.  
    
    * Queued mode to avoid overlapping TTS playback.  
    

    **Requirements:**  
    
    * Uber Eats Order Tracking integration installed and configured. 
    
    * A TTS engine configured in Home Assistant (e.g., Google Translate TTS).  
    
    * Media player entities to play announcements.  
    

    **Important Notes:**  
    
    * **Driver Address Sensor** = full formatted address (e.g., “200 W 34th St, New York, NY”). 
    
    * **Driver Street Sensor** = short street/cross-street label (e.g., “Atlantic Ave”) — this is what the speech prefers.  
    
    * Ensure your Uber Eats sensors update their **state** (not only attributes).  
    

  domain: automation

  input:
    # General
    user_name:
      name: User Name
      description: The user's name to include in TTS messages (e.g., Brandon)
      selector:
        text:

    # Active order binary sensor
    active_order_sensor:
      name: Active Order Binary Sensor
      description: Must be "on" when there is an active order.
      selector:
        entity:
          domain: binary_sensor

    # Core stage/name sensors
    order_stage_sensor:
      name: Order Stage Sensor
      description: e.g., picked up, en route, arriving, delivered
      selector:
        entity:
          domain: sensor

    driver_name_sensor:
      name: Driver Name Sensor
      selector:
        entity:
          domain: sensor

    # ETA / ETT + restaurant
    driver_eta_sensor:
      name: Driver ETA Sensor (clock time)
      description: e.g., "5:42 PM"
      selector:
        entity:
          domain: sensor

    driver_ett_sensor:
      name: Driver ETT Sensor (minutes remaining)
      description: e.g., "12 minutes"
      selector:
        entity:
          domain: sensor

    restaurant_name_sensor:
      name: Restaurant Name Sensor
      selector:
        entity:
          domain: sensor

    latest_arrival_sensor:
      name: Latest Arrival Sensor
      selector:
        entity:
          domain: sensor

    # Location inputs — named exactly as requested
    driver_address_sensor:
      name: Driver Address Sensor
      description: Full formatted address if available.
      selector:
        entity:
          domain: sensor

    driver_street_sensor:
      name: Driver Street Sensor
      description: Short street/cross-street label (preferred for speech).
      selector:
        entity:
          domain: sensor

    driver_quarter_sensor:
      name: Driver Borough/Quarter Senso
